Improve environment configuration
frctl/nunjucks-engine pull request #8
Opened 2019-03-10 10:24 UTC by allmarkedup

This PR switches `autoescape` to be enabled by default (as per the standard Nunjucks default behaviour) and adds the ability to pass options to the Nunjucks environment via the configuration object.

This is a breaking change so is intended be released as part of the v2.0 release of this adapter.

2019-03-10 13:35 UTC, LeBenLeBen approved these changes

2019-03-10 13:47 UTC, LeBenLeBen requested changes
I tried to enable autoescaping in an existing project and the preview is now bare HTML printed as text, it's not interpreted anymore by the browser. I don't know if something else is required on Fractal side but as is it looks like it will not work.

![Screenshot_2019-03-10 Collapse Liip Styleguide](https://user-images.githubusercontent.com/793344/54085890-5043c800-4343-11e9-8b6a-c144102424ef.png)

2019-03-10 14:04 UTC, allmarkedup commented
So the only change required (which means that this is a breaking change) is that preview layouts need to have their `{{ yield }}` variable changed to `{{ yield | safe }}` as the rendered output is no longer auto-escaped.

This will need documenting as part of the breaking changes included in the v2.0 release but that is probably worth doing as a separate PR for the release itself? What do you think?

2019-03-11 06:45 UTC, LeBenLeBen approved these changes
Fair enough! 👍

2019-03-11 19:28 UTC, merged